import i18n from "@/locales/i18n";
import { generateRandomString } from "@/utils/String";

export const dockerAppTypes = [
    i18n.global.k('全部'),
    i18n.global.k('实用工具'),
    i18n.global.k('开发&运维'),
    i18n.global.k('个人建站'),
    i18n.global.k('数据库'),
    i18n.global.k('网盘存储'),
];

const images = require.context('@/assets/docker/apps', false, /.*/);
const base_prefix = './';

export const dockerAppStore = [
    {
        name: 'Custom',
        isOfficial: false,
        author: 'Developers',
        link: 'https://hub.docker.com',
        desc: i18n.global.k('指定任意镜像进行应用部署'),
        type: 0,
        img: images(base_prefix + 'custom.svg'),
        deployInfo: {
            imageName: '',
            imageVersion: '',
            containerName: '',
            portMapping: '',
            envVars: '',
            volumeMounting: '',
            paramOptions: '',
        },
    },
    {
        name: 'kkTerminal',
        isOfficial: false,
        author: 'zyyzyykk',
        link: 'https://github.com/zyyzyykk/kkTerminal',
        desc: i18n.global.k('一个强大的Web SSH连接终端'),
        type: 1,
        img: images(base_prefix + 'kkterminal.svg'),
        deployInfo: {
            imageName: 'zyyzyykk/kkterminal',
            imageVersion: 'latest',
            containerName: 'kkterminal',
            portMapping: '3000:3000',
            envVars: 'PASSWORD=' + generateRandomString(16),
            volumeMounting: '$HOME/kkterminal/cloud:/cloud\n$HOME/kkterminal/log:/log\n$HOME/kkterminal/temp:/temp',
            paramOptions: '',
        },
    },
    {
        name: 'Code Server',
        isOfficial: false,
        author: 'codercom',
        link: 'https://github.com/coder/code-server',
        desc: i18n.global.k('运行VS Code并在浏览器中访问'),
        type: 2,
        img: images(base_prefix + 'vscode.svg'),
        deployInfo: {
            imageName: 'codercom/code-server',
            imageVersion: 'latest',
            containerName: 'codeserver',
            portMapping: '8080:8080',
            envVars: 'DOCKER_USER=$USER',
            volumeMounting: '$HOME/vscode/.config:/root/.config\n$HOME/vscode/project:/home/coder',
            paramOptions: '-u $(id -u):$(id -g)',
        },
    },
    {
        name: 'Drawio',
        isOfficial: false,
        author: 'jgraph',
        link: 'https://github.com/jgraph/docker-drawio',
        desc: i18n.global.k('Drawio是一款白板/绘图软件应用'),
        type: 1,
        img: images(base_prefix + 'drawio.svg'),
        deployInfo: {
            imageName: 'jgraph/drawio',
            imageVersion: 'latest',
            containerName: 'drawio',
            portMapping: '8080:8080\n8443:8443',
            envVars: '',
            volumeMounting: '',
            paramOptions: '',
        },
    },
    {
        name: 'MySQL',
        isOfficial: true,
        author: 'Docker Community',
        link: 'https://hub.docker.com/_/mysql',
        desc: i18n.global.k('全球最受欢迎的开源数据库'),
        type: 4,
        img: images(base_prefix + 'mysql.svg'),
        deployInfo: {
            imageName: 'mysql',
            imageVersion: 'latest',
            containerName: 'mysql',
            portMapping: '3306:3306',
            envVars: 'MYSQL_ROOT_PASSWORD=' + generateRandomString(16),
            volumeMounting: '$HOME/mysql:/var/lib/mysql',
            paramOptions: '',
        },
    },
    {
        name: 'Redis',
        isOfficial: true,
        author: 'Docker Community',
        link: 'https://hub.docker.com/_/redis',
        desc: i18n.global.k('世界上最快的NoSQL数据库'),
        type: 4,
        img: images(base_prefix + 'redis.svg'),
        deployInfo: {
            imageName: 'redis',
            imageVersion: 'latest',
            containerName: 'redis',
            portMapping: '6379:6379',
            envVars: '',
            volumeMounting: '$HOME/redis:/data',
            paramOptions: '',
        },
    },
    {
        name: 'Gitea',
        isOfficial: false,
        author: 'gitea',
        link: 'https://docs.gitea.com/installation/install-with-docker',
        desc: i18n.global.k('一个无痛的自托管Git服务'),
        type: 2,
        img: images(base_prefix + 'gitea.svg'),
        deployInfo: {
            imageName: 'gitea/gitea',
            imageVersion: 'latest',
            containerName: 'gitea',
            portMapping: '3000:3000\n222:22',
            envVars: '',
            volumeMounting: '$HOME/gitea:/data\n/etc/timezone:/etc/timezone:ro\n/etc/localtime:/etc/localtime:ro',
            paramOptions: '',
        },
    },
    {
        name: 'OpenList',
        isOfficial: false,
        author: 'OpenList Team',
        link: 'https://github.com/OpenListTeam/OpenList',
        desc: i18n.global.k('一个支持多存储的文件列表程序'),
        type: 5,
        img: images(base_prefix + 'openlist.svg'),
        deployInfo: {
            imageName: 'openlistteam/openlist',
            imageVersion: 'latest',
            containerName: 'openlist',
            portMapping: '5244:5244',
            envVars: 'UMASK=022\nOPENLIST_ADMIN_PASSWORD=' + generateRandomString(16),
            volumeMounting: '$HOME/openlist:/opt/openlist/data',
            paramOptions: '-u $(id -u):$(id -g)',
        },
    },
];
